### ISSUE TITLE
error: 'WindowsNamespace' has not been declared

### ISSUE THREAD

**Issue by kuh3h3** [MediaArea/MediaInfoLib#1079]
C:/Users/kuh3h/Downloads/media-autobuild_suite/build/libmediainfo-git/Source/ThirdParty/aes-gladman/aes.h:93:3: warning: 'align' attribute directive ignored [-Wattributes]
 } aes_decrypt_ctx;
   ^~~~~~~~~~~~~~~
C:/Users/kuh3h/Downloads/media-autobuild_suite/build/libmediainfo-git/Source/MediaInfo/Reader/Reader_libcurl.cpp: In member function 'virtual size_t MediaInfoLib::Reader_libcurl::Format_Test_PerParser_Continue(MediaInfoLib::MediaInfo_Internal*)':
C:/Users/kuh3h/Downloads/media-autobuild_suite/build/libmediainfo-git/Source/MediaInfo/Reader/Reader_libcurl.cpp:1153:41: error: 'WindowsNamespace' has not been declared
                                         WindowsNamespace::Sleep(1000);
                                         ^~~~~~~~~~~~~~~~
C:/Users/kuh3h/Downloads/media-autobuild_suite/build/libmediainfo-git/Source/MediaInfo/Reader/Reader_libcurl.cpp:1237:37: error: 'WindowsNamespace' has not been declared
                                     WindowsNamespace::Sleep(1000);
                                     ^~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.

**Comment by hydra3333** [comment]
yes,
cross-compilation killed stone dead by WindowsNamespace error
likely introduced by b90ca92a390639baf2abe25a8f7b5366e79a808a

**Comment by JeromeMartinez** [comment]
Weird... Which compiler? I'll add a test on the C++ version (as the issue is with C++17).
(if there are still problem, or in the future, there are other possibilities like avoiding to set "using namespace std" so early, but more work so I am lazy to do it for the moment)

**Comment by JeromeMartinez** [comment]
Please try again with code in master branch.
https://github.com/MediaArea/MediaInfoLib/pull/1080

**Comment by kuh3h3** [comment]
kuh3h3@DESKTOP-R0PM5LB /trunk
$ gcc -v
Using built-in specs.
COLLECT_GCC=C:\Users\kuh3h\Downloads\media-autobuild_suite\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/Users/kuh3h/Downloads/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-8-20181214/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=ada,c,lto,c++,objc,obj-c++,fortran --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev1, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 8.2.1 20181214 (Rev1, Built by MSYS2 project)
kuh3h3@DESKTOP-R0PM5LB /trunk
$ uname -a
MINGW64_NT-10.0 DESKTOP-R0PM5LB 2.11.2(0.329/5/3) 2018-11-26 09:22 x86_64 Msys
kuh3h3@DESKTOP-R0PM5LB /trunk

**Comment by JeromeMartinez** [comment]
OK, so with GCC "windows.h" is declared elsewhere without the added namespace, the method is not for everywhere, good to know.
(the issue will come back for GCC when C++17 will be in force, I have some time here for changing how it is handled)
